Use junit in functional tests
minio/minio-java pull request #1133
Opened 2020-12-04 12:59 UTC by balamurugana

2020-12-18 07:20 UTC, ebozduman requested changes
Functional test run fails...
```
$ ./gradlew runFunctionalTest` also fails with error.
> Task :functional:runFunctionalTest FAILED

FAILURE: Build failed with an exception.
```

2020-12-18 07:38 UTC, ebozduman commented on functional/FunctionalTest.java
> +      Assert.assertEquals(
Bala explained to me that the `Assert.assertNull` actually means "make sure the condition is **NOT** Null".
So, all my comments are wrong. Resolved all of them.

2020-12-18 08:33 UTC, ebozduman approved these changes
LGTM

2020-12-22 20:45 UTC, kannappanr approved these changes
LGTM

2020-12-22 20:45 UTC, merged