Mint - Add environment variable RUN_ON_FAIL
minio/minio-java pull request #1180
Opened 2021-04-07 11:24 UTC by iternity-dotcom

Refering to https://github.com/minio/minio/issues/11996

## Description
By setting the variable `RUN_ON_FAIL` all tests from minio-java are executed independent of failures.

 ## Motivation and Context
A single failing test from the test package causes all the remaining tests to be skipped.

## How to test this PR?
`RUN_ON_FAIL=1`
At least two tests must fail.

`RUN_ON_FAIL=0`
The behavior is not changed if the environment variable is not set or equals 0.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-06-16 09:13 UTC, balamurugana commented on functional/FunctionalTest.java
> +    isRunOnFail = System.getenv("RUN_ON_FAIL") != null && System.getenv("RUN_ON_FAIL").equals("1");
This flag is only useful for `mint` mode. You could move this assignment line #3810

2021-06-16 09:13 UTC, balamurugana commented on functional/FunctionalTest.java
> +    if (isRunOnFail) {
This is only applicable to `mint` mode, you could move this check to line #426.

2021-06-16 12:23 UTC, balamurugana approved these changes

2022-01-13 04:25 UTC, balamurugana requested changes

2022-01-13 04:25 UTC, balamurugana commented on functional/FunctionalTest.java
> +          System.getenv("RUN_ON_FAIL") != null && System.getenv("RUN_ON_FAIL").equals("1");
Just use `isRunOnFail = "1".equals(System.getenv("RUN_ON_FAIL"))`

2022-01-13 05:08 UTC, andrebruch commented on functional/FunctionalTest.java
> +          System.getenv("RUN_ON_FAIL") != null && System.getenv("RUN_ON_FAIL").equals("1");
@balamurugana done 👍

2022-01-13 14:00 UTC, balamurugana approved these changes

2022-01-13 17:56 UTC, harshavardhana approved these changes

2022-01-13 17:56 UTC, merged