Fix issue with downloading objects inside a folder
minio/minio-java pull request #1284
Opened 2022-01-04 19:23 UTC by Aeltumn

This is a fix for a small issue I ran into. I'm doing the following:
```
DownloadObjectArgs.builder()
                    .bucket("my-bucket")
                    .object("production/object.zip")
                    .filename("downloads/object.zip")
                    .build()
                    ```
                    
And I got the following error:
```
java.nio.file.NoSuchFileException: /app/downloads/object.zip.-CP/Qwejp1PCQEEA=.part.minio
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
        at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
        at io.minio.MinioClient.downloadObject(MinioClient.java:1101) ~[common.jar:?]
```

The issue was resolved after removing slashes from the etag to prevent the temporary file from being placed in a subfolder.

2022-01-04 19:33 UTC, balamurugana requested changes

2022-01-04 19:33 UTC, balamurugana commented on api/src/main/java/io/minio/MinioClient.java
> +    String tempFilename = filename + "." + stat.etag().replaceAll("/", "") + ".part.minio";
Please use `S3Escape.encode(stat.etag())` instead of removing `/`.

2022-01-04 20:16 UTC, harshavardhana approved these changes

2022-01-05 01:20 UTC, balamurugana approved these changes

2022-01-05 01:22 UTC, merged