Fix list canned policies
minio/minio-java pull request #1289
Opened 2022-01-21 17:10 UTC by Sam-Kramer

Currently, the returned map when listing all canned policies will return <String, LinkedHashMap> due to the policy (value) being a json blob. There's really no nice way to force jackson to treat it as raw json, thus my suggestion is to just treat it as a JsonNode, which then the user can either convert to a String, or if they've a pojo if they have it. 

First commit shows how the unit test fix exposes the failure, and the second commit contains the actual fix.

2022-01-21 17:35 UTC, balamurugana requested changes

2022-01-24 11:23 UTC, Sam-Kramer commented on adminapi/src/main/java/io/minio/admin/MinioAdminClient.java
> +  public Map<String, JsonNode> listCannedPolicies()
That's fair, to keep backward compatibility, and to deal with this as the madmin client does, we'll just convert it to a string.

2022-01-24 16:38 UTC, harshavardhana submitted a review, later dismissed

2022-01-24 17:46 UTC, harshavardhana approved these changes

2022-01-26 00:00 UTC, balamurugana approved these changes

2022-01-26 00:00 UTC, merged

2022-01-26 10:30 UTC, Sam-Kramer commented
Any chance we can get a release for this @balamurugana / @harshavardhana ?

2022-01-26 16:41 UTC, harshavardhana commented
> Any chance we can get a release for this @balamurugana / @harshavardhana ?

Soon @Sam-Kramer