Add async support
minio/minio-java pull request #1308
Opened 2022-03-09 09:51 UTC by balamurugana

Signed-off-by: Bala.FA <bala@minio.io>

2022-03-17 07:05 UTC, harshavardhana commented
is this a breaking change? @balamurugana

2022-03-17 07:10 UTC, balamurugana commented
> is this a breaking change? @balamurugana 

No. The existing functionalities work as is in addition to async APIs.

2022-04-11 16:37 UTC, anjalshireesh requested changes

2022-04-11 16:37 UTC, anjalshireesh commented on api/src/main/java/io/minio/ListObjectsV1Response.java
> +/** Response class of {@link S3Base#listObjectsV1}. */
```suggestion
/** Response class of {@link S3Base#listObjectsV1Async}. */
```

2022-04-11 16:37 UTC, anjalshireesh commented on api/src/main/java/io/minio/ListObjectsV2Response.java
> +/** Response class of {@link S3Base#listObjectsV2}. */
```suggestion
/** Response class of {@link S3Base#listObjectsV2Async}. */
```

2022-04-11 16:37 UTC, anjalshireesh commented on api/src/main/java/io/minio/ListenBucketNotificationArgs.java
> + * Argument class of {@link MinioClient#listenBucketNotification} and {@link
```suggestion
 * Argument class of {@link MinioAsyncClient#listenBucketNotification} and {@link
```

2022-04-11 16:37 UTC, anjalshireesh commented on api/src/main/java/io/minio/StatObjectResponse.java
> +/** Response of {@link MinioAsyncClient#statObject} and {@link MinioClient#statObject}. */
```suggestion
/** Response of {@link S3Base#statObjectAsync} */
```

2022-04-21 06:17 UTC, balamurugana commented on api/src/main/java/io/minio/StatObjectResponse.java
> +/** Response of {@link MinioAsyncClient#statObject} and {@link MinioClient#statObject}. */
done

2022-04-21 06:17 UTC, balamurugana commented on api/src/main/java/io/minio/ListenBucketNotificationArgs.java
> + * Argument class of {@link MinioClient#listenBucketNotification} and {@link
done

2022-04-21 06:18 UTC, balamurugana commented on api/src/main/java/io/minio/ListObjectsV2Response.java
> +/** Response class of {@link S3Base#listObjectsV2}. */
done

2022-04-21 06:18 UTC, balamurugana commented on api/src/main/java/io/minio/ListObjectsV1Response.java
> +/** Response class of {@link S3Base#listObjectsV1}. */
done

2022-04-22 16:36 UTC, anjalshireesh approved these changes
LGTM, one minor suggestion

2022-04-26 02:49 UTC, harshavardhana commented on api/src/main/java/io/minio/S3Base.java
> +    throw new RuntimeException(ex);
PTAL @balamurugana

2022-04-26 03:31 UTC, harshavardhana approved these changes

2022-04-27 06:42 UTC, anjalshireesh approved these changes

2022-04-27 08:40 UTC, merged