Add overwrite flag to downloadObject() API.
minio/minio-java pull request #1321
Opened 2022-04-13 17:20 UTC by balamurugana

When setting overwrite flag to true for DownloadObjectArgs makes
overwriting destination file if it exists.

Signed-off-by: Bala.FA <bala@minio.io>

2022-04-13 17:45 UTC, harshavardhana requested changes
When we overwrite do we automatically truncate the file?

2022-04-13 17:52 UTC, balamurugana commented
> When we overwrite do we automatically truncate the file?

No. `downloadObject()` downloads object's data into a temporary file named `String tempFilename = filename + "." + S3Escaper.encode(stat.etag()) + ".part.minio";` (If this temporary file exists, it is removed before downloading to it) and renamed to actual destination file.

2022-04-13 18:11 UTC, harshavardhana commented
> > When we overwrite do we automatically truncate the file?
> 
> No. `downloadObject()` downloads object's data into a temporary file named `String tempFilename = filename + "." + S3Escaper.encode(stat.etag()) + ".part.minio";` (If this temporary file exists, it is removed before downloading to it) and renamed to actual destination file.

👍🏽

2022-04-13 18:11 UTC, harshavardhana approved these changes

2022-04-14 01:22 UTC, harshavardhana approved these changes

2022-04-21 06:20 UTC, harshavardhana approved these changes

2022-04-21 06:21 UTC, merged