Enhancement of the MinIO admin client functionality with the group function
minio/minio-java pull request #1343
Opened 2022-06-24 16:45 UTC by Vedat-D

Three functions have been added to the client.

A function (**addUpdateRemoveGroup**) to add a group with optional group membership or to update the membership of a group or to delete a group.
**Example**: 
Create an empty group: 
`minioClient.addUpdateRemoveGroup(groupName, Status.ENABLED, null, false);`
Delete a group: 
`minioClient.addUpdateRemoveGroup(groupName, Status.ENABLED, null, true);`
Update membership of group :
`minioClient.addUpdateRemoveGroup(groupId, Status.ENABLED, groupMembers, false);`

A function (**getGroupInfo**) to get information of a group.
**Example**: 
Get info of a group:
 `GroupInfo groupInfo = minioClient.getGroupInfo(groupName);`

A function (**listGroups**) to list all groups.
**Example**: 
List all groups: 
`List<String> groupsMinio = minioClient.listGroups();`

I have extracted the enum status but left it in the class UserInfo so as not to cause any breaking changes.

2022-06-24 17:16 UTC, balamurugana requested changes

2022-06-24 19:16 UTC, harshavardhana requested changes

2022-06-24 19:16 UTC, harshavardhana commented on adminapi/src/main/java/io/minio/admin/GroupAddUpdateRemoveInfo.java
> + * (C) 2021 MinIO, Inc.
```suggestion
 * (C) 2022 MinIO, Inc.
```

2022-06-24 19:16 UTC, harshavardhana commented on adminapi/src/main/java/io/minio/admin/GroupInfo.java
> + * (C) 2021 MinIO, Inc.
```suggestion
 * (C) 2022 MinIO, Inc.
```

2022-06-24 19:16 UTC, harshavardhana commented on adminapi/src/main/java/io/minio/admin/Status.java
> +package io.minio.admin;
missing copyright header..

2022-06-25 04:45 UTC, balamurugana approved these changes

2022-07-10 19:36 UTC, Vedat-D commented
Hello together, what is the status here?

2022-09-24 04:26 UTC, harshavardhana approved these changes

2022-09-24 04:27 UTC, merged