examples:add TLS client example
minio/minio-java pull request #1439
Opened 2023-04-11 09:12 UTC by dormanze

Users who use the minio client for the first time do not know how to write the SSL client code.
I suggest adding an TSL example.

2023-04-11 11:31 UTC, balamurugana requested changes

2023-04-11 11:31 UTC, balamurugana commented on examples/MinioClientWithTLS.java
This example is not needed. Refer https://minio-java.min.io/io/minio/S3Base.html#ignoreCertCheck-- and https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/http/HttpUtils.java

2023-04-11 12:13 UTC, dormanze commented on examples/MinioClientWithTLS.java
Thank you for your reply.
It's nice that [HttpUtils.java](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/http/HttpUtils.java) provides default certificate support, but I think we should provide java-friendly jks or p12-type certificate support, and I'll be happy to contribute this part of the code if you agree.

2023-04-11 12:37 UTC, balamurugana commented on examples/MinioClientWithTLS.java
Feel free to send a PR adding the support to `HttpUtils.java`

2023-04-12 08:20 UTC, dormanze commented on examples/MinioClientWithTLS.java
I have added support for jks and p12 certificates in addition to the original default support for pem certificates. Please review my pr.

2023-04-12 09:03 UTC, balamurugana requested changes

2023-04-12 09:03 UTC, balamurugana commented on api/src/main/java/io/minio/http/HttpUtils.java
> +  public static OkHttpClient enableExternalCertificates(OkHttpClient httpClient)
We do not need this wrapper. Users know what public methods to call.

2023-04-12 10:37 UTC, dormanze commented on api/src/main/java/io/minio/http/HttpUtils.java
> +    String keystoreType = System.getenv("SSL_CERT_KEYSTORE_TYPE");
It's good for safety.

2023-04-13 01:16 UTC, balamurugana requested changes

2023-04-13 01:16 UTC, balamurugana commented on api/src/main/java/io/minio/http/HttpUtils.java
> +  public static OkHttpClient newHttpClientByP12Cert(String truststorePath,
We don't want to create new http clients. Instead we would need to enable external certs. Over all this PR should be like below
```java
  private static OkHttpClient enableJKSPKCS12Certificates(
      OkHttpClient httpClient,
      String trustStorePath,
      String trustStorePassword,
      String keyStorePath,
      String keyStorePassword,
      boolean pkcs12)
      throws GeneralSecurityException, IOException {
    if (trustStorePath == null || trustStorePath.isEmpty()) {
      throw new IllegalArgumentException("trust store path must be provided");
    }
    if (trustStorePassword == null) {
      throw new IllegalArgumentException("trust store password must be provided");
    }
    if (keyStorePath == null || keyStorePath.isEmpty()) {
      throw new IllegalArgumentException("key store path must be provided");
    }
    if (keyStorePassword == null) {
      throw new IllegalArgumentException("key store password must be provided");
    }

    SSLContext sslContext = SSLContext.getInstance("TLS");
    KeyStore trustStore = KeyStore.getInstance("JKS");
    KeyStore keyStore = KeyStore.getInstance(pkcs12 ? "PKCS12" : "JKS");
    try (FileInputStream trustInput = new FileInputStream(truststorePath);
        FileInputStream keyInput = new FileInputStream(keystorePath); ) {
      trustStore.load(trustInput, trustStorePassword.toCharArray());
      keyStore.load(keyInput, keyStorePassword.toCharArray());
    }
    TrustManagerFactory trustManagerFactory =
        TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
    trustManagerFactory.init(trustStore);

    KeyManagerFactory keyManagerFactory =
        KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
    keyManagerFactory.init(keyStore, keyStorePassword.toCharArray());

    sslContext.init(
        keyManagerFactory.getKeyManagers(),
        trustManagerFactory.getTrustManagers(),
        new java.security.SecureRandom());

    return httpClient
        .newBuilder()
        .sslSocketFactory(
            sslContext.getSocketFactory(),
            (X509TrustManager) trustManagerFactory.getTrustManagers()[0])
        .build();
  }

  public static OkHttpClient enableJKSCertificates(
      OkHttpClient httpClient,
      String trustStorePath,
      String trustStorePassword,
      String keyStorePath,
      String keyStorePassword)
      throws GeneralSecurityException, IOException {
    return enableJKSPKCS12Certificates(
        httpClient, trustStorePath, trustStorePassword, keyStorePath, keyStorePassword, false);
  }

  public static OkHttpClient enablePKCS12Certificates(
      OkHttpClient httpClient,
      String trustStorePath,
      String trustStorePassword,
      String keyStorePath,
      String keyStorePassword)
      throws GeneralSecurityException, IOException {
    return enableJKSPKCS12Certificates(
        httpClient, trustStorePath, trustStorePassword, keyStorePath, keyStorePassword, true);
  }
```

2023-04-13 01:16 UTC, balamurugana commented on examples/MinioClientWithTLS.java
Remove this obvious example.

2023-04-13 01:30 UTC, dormanze commented on api/src/main/java/io/minio/http/HttpUtils.java
> +                                                      String keyStorePassword)
Verify that the certificate file path is required.

2023-04-13 01:31 UTC, dormanze commented on examples/MinioClientWithTLS.java
ok

2023-04-13 01:51 UTC, balamurugana commented
@dormanze Please fix CI failures

2023-04-13 02:29 UTC, dormanze commented
> @dormanze Please fix CI failures

Copy that, fixed CI.

2023-04-13 02:45 UTC, balamurugana approved these changes

2023-04-13 12:41 UTC, dormanze commented
@harshavardhana Please approve my pr.

2023-04-13 18:09 UTC, harshavardhana approved these changes

2023-04-13 18:09 UTC, merged